global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "4maths-app"
    static_configs:
      - targets: ["4maths-app:18080"] # Nó sẽ lấy dữ liệu từ app của ông

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"] # Dùng để theo dõi CPU/RAM của EC2
