name: C++ Docker CI-CD

# Chạy tự động mỗi khi có code push lên nhánh main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ GitHub về server ảo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Đăng nhập vào Docker Hub (Để đẩy image lên sau khi build)
      # Ông cần tạo account trên Docker Hub và add Secret vào GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 4maths
          password: ${{ dckr_pat_4YJLuGqCqwoUMlEcBeG08v9phGg }}

      # Bước 3: Thiết lập Docker Buildx (Công cụ build nâng cao)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Bước 4: Build và Push Image lên Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./infra/Dockerfile
          push: true
          # Thay 'your-username' bằng tên tài khoản Docker Hub của ông
          tags: your-username/coursera-lite:latest
